auctions/urls.py
from django.urls import path
from . import views

app_name = "auctions"
urlpatterns = [

    # Listing paths
    path("", views.index, name="index"),
    path("login/", views.loginview, name="login"),
    path("logout/", views.logoutview, name="logout"),
    path("register/", views.register, name="register"),
    path("addlisting/", views.add_listing, name="addlisting"),
    path("viewlisting/<int:listing_id>", views.view_listing, name="viewlisting"),
    path("closedlisting/", views.closed_listing, name="closedlisting"),

    # Watchlist paths
    path("watchlistswitch/<int:listing_id>", views.watchlist_switch, name="watchlistswitch"),
    path("watchlist/", views.watchlist, name="watchlist"),

    # Categories
    path("category/", views.category, name="category"),
    path("category/<str:category>", views.list_categories, name="categorylist"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from datetime import datetime


# Categories
categories = [
    ('misc', 'misc'),
    ('computers', 'computers'),
    ('toys', 'toys'),
    ('pets', 'pets'),
    ('beauty', 'beauty'),
    ('video games', 'video games'),
    ('auto', 'auto'),
    ('clothing', 'clothing'),
]


ACTIVE_CHOICES = [
    ('Yes', 'Yes'),
    ('No', 'No'),
]


class User(AbstractUser):

    def __str__(self):
        return f"{self.username}"


class Listing(models.Model):
    listing_owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="listing_owner")
    listing_title = models.CharField(max_length=100)
    listing_description = models.TextField(max_length=1200)
    listing_img = models.URLField(null=True, blank=True, max_length=250)
    created_on = models.DateTimeField(auto_now=True)
    starting_price = models.DecimalField(
        decimal_places=2, max_digits=10, default=1.00)
    current_price = models.DecimalField(
        decimal_places=2, max_digits=10, default=0.00)

    # From above categories list
    category = models.CharField(
        max_length=30, choices=categories, default='misc')
    # From active or inactive list
    closed_auction = models.CharField(
        max_length=10, choices=ACTIVE_CHOICES, default="No")

    class Meta:
        ordering = ['-created_on']

    # Redirect for comments and bids
    def get_absolute_url(self):
        return reverse('auctions:viewlisting', args=[str(self.id)])

    def __str__(self):
        return f"Title: {self.listing_title}, Price: ${self.starting_price}, Posted By: {self.listing_owner}"


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, null=True)
    bid_amount = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return f"{self.user}'s bid on {self.listing} is {self.bid_amount}"


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.listing}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, null=True)
    content = models.TextField(max_length=500, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.content}"

auctions/forms.py
from django.contrib.auth.models import AbstractUser
from django.forms import ModelForm
from django import forms
from .models import AbstractUser, Bid, Comment, Listing


class ListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ('listing_title', 'listing_description',
                  'listing_img', 'category', 'closed_auction')
        ordering = ['-id']
        labels = {'listing_title': ('Item Name'), 'listing_description': ('Seller Note'), 'listing_img': (
            'Image URL'), 'closed_auction': ('Closed Auction?')}

        widgets = {
            'listing_title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Think of a name that sells your product.'}),
            'listing_description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Tell potential bidders more about this item...'}),
            'listing_img': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'https://cutebunnyrabbits.jpg'}),
            'category': forms.Select(attrs={'class': 'form-control text-capitalize'}),
            'closed_auction': forms.HiddenInput(attrs={'class': 'form-control'}),
        }


class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ('bid_amount',)
        labels = {'bid_amount': ('Your Bid')}

        widgets = {
            'bid_amount': forms.NumberInput(attrs={'step': 00.50, 'class': 'form-control', 'style': 'width:50%', 'min': 0, 'title': '', 'placeholder': ''})
        }


class CloseForm(ModelForm):
    class Meta:
        model = Listing
        fields = ('closed_auction',)
        labels = {'closed_auction': ('Close Auction?')}

        widgets = {
            'closed_auction': forms.Select(attrs={'class': 'form-control'})
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {'content': (''), }

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control w-100', 'placeholder': 'Add a comment about this item...'}),
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import ListingForm, BidForm, CloseForm, CommentForm
from .models import User, Listing, Bid, Watchlist, Comment, categories
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):
    listings = Listing.objects.filter(closed_auction="No")
    most_recent = listings.order_by('-created_on')[:5]
    w_list = []

    if not request.user.is_authenticated:
        w_list = None
    else:
        watchlist = Watchlist.objects.filter(user=request.user)

        for item in watchlist:
            w_list.append(item)

    context = {
        "listings": listings,
        "w_list": w_list,
        "recent": most_recent
    }

    return render(request, "auctions/index.html", {"context": context})


def closed_listing(request):
    listings = Listing.objects.filter(closed_auction="Yes")
    w_list = []

    if not request.user.is_authenticated:
        w_list = None
    else:
        watchlist = Watchlist.objects.filter(user=request.user)

        for item in watchlist:
            w_list.append(item)

    if not listings:
        listings = None

    context = {
        "listings": listings,
        "w_list": w_list,
        "category": category
    }

    return render(request, "auctions/closedlisting.html", {"context": context})


def loginview(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # POST route at login
        # Check if authentication unsuccessful
        if user is None:
            messages.error(request, "Login unsuccessful")
            return render(request, "auctions/login.html")
        else:
            # Successful
            login(request, user)
            messages.info(request, "Logged in successfully")
            return HttpResponseRedirect(reverse("auctions:index"))
    else:
        # Render form on GET
        return render(request, "auctions/login.html")


def logoutview(request):
    logout(request)
    messages.warning(request, "Logged out successfully")
    return HttpResponseRedirect(reverse("auctions:login"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            messages.error(request, "Passwords must match.")
            return render(request, "auctions/register.html")

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            messages.error(request, "Username already taken.")
            return render(request, "auctions/register.html")
        login(request, user)
        messages.info(request, "Logged in successfully.")
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def not_found(request):
    return render(request, 'auctions/error.html')


from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ListingForm
from .models import Listing, User

@login_required
def add_listing(request):
    user = request.user

    if request.method == "GET":
        form = ListingForm()
        return render(request, "auctions/addlisting.html", {"form": form})

    else:
        form = ListingForm(request.POST, request.FILES)

        if form.is_valid():
            try:
                newlisting = form.save(commit=False)
                newlisting.listing_owner = user
                newlisting.save()

                messages.success(request, "Your listing has been saved.")
                return redirect("auctions:index")

            except Exception as e:
                messages.error(request, f"There was an error saving your listing: {e}")
                return render(request, "auctions/addlisting.html", {"form": form})

        else:
            messages.error(request, "There was an error with the form. Please correct it.")
            return render(request, "auctions/addlisting.html", {"form": form})


@login_required
def view_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    bids = Bid.objects.filter(listing=listing)
    comments = Comment.objects.filter(listing=listing)
    list_item = Watchlist.objects.filter(
        user=request.user, listing__id=listing_id)
    closed_status = None

    all_bids = []  # Set an empty bid list to get all bids if any exist
    # Set highest bid to 0 in case there are no bids
    highest_bid = listing.starting_price
    highest_bidder = ''
    winner = ''

    if bids:
        bid_list = list(bids)  # Convert Queryset to a list

        for index in bid_list:
            all_bids.append(index)
        # Get the highest bid from all_bids
        highest_bid = all_bids[-1].bid_amount
        # Get the highest bidder from all_bids
        highest_bidder = all_bids[-1].user
        listing.starting_price = highest_bid

    else:
        highest_bid  # Else highest bid is 0
        highest_bidder  # Else highest bid is blank

    if listing.closed_auction == "Yes":
        closed_status = "closed"

    if request.method == "GET":
        bid_form = BidForm()
        close_form = CloseForm()
        comment_form = CommentForm()
        close_form.initial['closed_auction'] = listing.closed_auction

        if closed_status == "closed":
            winner = highest_bidder

        context = {
            "listing": listing,
            "item": list_item,
            "bids": bids,
            "bid_form": bid_form,
            "close_form": close_form,
            "comment_form": comment_form,
            "comments": comments,
            "highest_bid": highest_bid,
            "highest_bidder": highest_bidder,
            "winner": winner,
            "closed_status": closed_status
        }

        return render(request, "auctions/viewlisting.html", {"context": context})

    else:  # On POST, allow a user to bid on an item
        try:
            form_type = request.POST.get("form_type")
            form = None

            if form_type == "form_bid": # from hidden value field in viewlisting.html
                form = BidForm(request.POST)

            if form_type == "form_close": # from hidden value field in viewlisting.html
                form = CloseForm(request.POST, instance=listing)

            if form_type == "form_comment": # from hidden value field in viewlisting.html
                form = CommentForm(request.POST, instance=listing)

            if form and form.is_valid():
                if form_type == "form_bid":
                    bid_amount = request.POST.get("bid_amount")
                    bid_value = form.cleaned_data['bid_amount']

                    if bid_value <= highest_bid:
                        raise ValueError
                    Bid.objects.create(
                        listing=listing, user=request.user, bid_amount=bid_value)

                    # Update the current price to the latest bid price if the form is valid
                    bid_price = Listing.objects.filter(
                        pk=listing_id).update(current_price=bid_value)
                    messages.info(request, "Your bid was accepted.")

                if form_type == "form_close":
                    closed_auction = request.POST.get("closed_auction")
                    messages.info(request, "Listing closed.")
                    form.save()

                if form_type == "form_comment":
                    comment = request.POST.get("content")
                    Comment.objects.create(
                        listing=listing, user=request.user, content=comment)
                    messages.success(request, "Your comment has been posted.")

                return HttpResponseRedirect(listing.get_absolute_url())

            return redirect("auctions:index")

        except ValueError:
            bid_amount = request.POST.get("bid_amount")
            close_form = CloseForm()

            context = {
                "listing": listing,
                "item": list_item,
                "bids": bids,
                "form": form,
                "highest_bidder": highest_bidder,
                "highest_bid": highest_bid
            }

            messages.error(
                request, f"Your bid of ${bid_amount} must be higher that the last ${highest_bid} bid.")
            return render(request, "auctions/viewlisting.html", {"context": context})


@login_required
def watchlist_switch(request, listing_id):
    listing = Listing.objects.get(id=int(listing_id))

    try:  # Check if the listing item exists in the user's watchlist
        watchlist_entry = Watchlist.objects.all().filter(
            listing__id=listing_id, user__id=request.user.id)
    except:  # else return None
        watchlist_entry = None

    if watchlist_entry:  # If it exists, give the option to remove
        watchlist_entry.delete()
        messages.success(request, f"Item removed from watchlist.")
        return HttpResponseRedirect(listing.get_absolute_url())
    else:  # If it doesn't, create a new wishlist item
        new_watchlist_entry = Watchlist(user=request.user, listing=listing)
        new_watchlist_entry.save()
        messages.success(request, f"Item added to watchlist.")

auctions/templates/auctions/addlisting.html
{% extends "auctions/layout.html" %} {% block body %} {% load static %} {% load humanize %}

<h3 class="fw-bold text-center mb-5 bg-primary text-light p-3">Add Listing</h3>
<div class="container mt-5 p-4 shadow-lg bg-light rounded">
    <form action="{% url 'auctions:addlisting' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <label for="starting_price">Starting Price:</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">$</span>
            </div>
            <input type="number" class="form-control" name="starting_price" placeholder="1.00">
        </div>
        <input class="btn btn-outline-primary btn-md" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %} {% block body %} {% load static %} {% load humanize %}

<h3 class="fw-bold text-center mb-5 bg-info text-white p-3">{{ categories|length }} Categories</h3>
<div class="container">
    <div class="d-flex flex-wrap justify-content-center">
        {% for item in categories %}
        <div class="col-md-4 col-sm-6 mb-4">
            <div class="list-group-item shadow-lg text-center border-0 py-5"
                style="font-family: 'Julius Sans One', sans-serif;">
                <form method="POST" class="form-group" action="{% url 'auctions:categorylist' item.0 %}">
                    {% csrf_token %}
                    <input type="submit" class="h4 bg-white text-secondary border-0 p-2" value="{{ item.0|capfirst }}">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/categorylist.html
{% extends "auctions/layout.html" %} {% block body %} {% load static %} {% load humanize %}

<h3 class="fw-bold text-center bg-info text-white p-3">Category: {{ context.category|capfirst }}</h3>
<hr class="my-4">
<div class="container ">
    <div class="d-flex flex-wrap justify-content-center">
        {% if context.listings %}
        {% for item in context.listings %}
        {% if item.closed_auction == "No" %}
        <div class="col-md-4 col-sm-6 mb-4">
            <a href="{% url 'auctions:viewlisting' item.id %}" class="text-decoration-none text-dark">
                <div class="card shadow-lg border-0 rounded-0 m-2" style="width:18rem; height: 600px; overflow: hidden;">
                    <div class="image-container">
                        {% if item.listing_img %}
                        <img src="{{ item.listing_img }}" alt="{{ item.listing_title }}"
                            title="{{ item.listing_title }}" style="width: 100%; height: 100%; object-fit: scale-down;">
                        {% else %}
                        <img src="https://res.cloudinary.com/angelrodriguez/image/upload/v1608836297/cs50_commerce_project/bicycle-emoji.svg"
                            alt="default image" title="default image"
                            style="width: 100%; height: 100%; object-fit: contain;">
                        <span class="lead text-center">Default. No Image Posted.</span>
                        {% endif %}
                    </div>
                    <h4 class="card-title text-center text-white bg-dark p-1">{{ item.listing_title }}</h4>
                    <div class="card-body text-center">
                        <p><em>Listed By: {{ item.listing_owner|capfirst }}</em></p>
                        <p>Added: {{ item.created_on }}</p>
                        <h5>Starting: ${{ item.starting_price|floatformat:2|intcomma }}</h5>
                        <h5>
                            {% if item.current_price == 0 %}
                            <mark>No Bids Yet.</mark>
                            {% else %}
                            <mark>Current: ${{ item.current_price|floatformat:2|intcomma }}</mark>
                            {% endif %}
                        </h5>
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <div class="col-12 text-center">
            <h3 class="font-weight-light">Nothing added to {{ context.category|capfirst }}, yet.</h3>
            <img src="https://res.cloudinary.com/angelrodriguez/image/upload/v1608839580/cs50_commerce_project/undraw_blank_canvas_3rbb.svg"
                class="img-fluid" alt="empty box">
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %} {% block body %} {% load static %} {% load humanize %}

<div class="container text-center mt-5">
    <h3>Page Not Found - Error 404</h3>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <img src="https://res.cloudinary.com/angelrodriguez/image/upload/v1608820017/cs50_commerce_project/undraw_warning_cyit.svg"
                alt="Not Found" class="img-fluid">
        </div>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Bidstrocity{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'auctions/shop-store-icon.ico' %}">
</head>
<body class="d-flex flex-column min-vh-100 bg-white">
    <nav class="navbar navbar-expand-lg navbar-light bg-white p-1">
        <div class="container-fluid">
            <a class="navbar-brand pr-5" href="{% url 'auctions:index' %}">
                <span class="display-5 font-weight-light fs-4 fs-md-3">
                    <span class="text-primary">Bid</span><span class="text-danger">stro</span><span class="text-warning">city</span>
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <div class="d-flex w-100 justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings <span
                                    class="badge badge-dark badge-pill">{{ listings_total }}</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:closedlisting' %}">Closed Listings <span
                                    class="badge badge-danger badge-pill">{{ closed_total }}</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:category' %}">Categories <span
                                    class="badge badge-info badge-pill">{{ category_count }}</span></a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:watchlist' %}">My Watchlist <span
                                    class="badge badge-warning badge-pill">{{ length }}</span></a>
                        </li>
                        <li class="nav-item pl-3">
                            <a class="nav-link border-left" href="{% url 'auctions:addlisting' %}">Add Listing</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-primary" href="#" id="navbarDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <span><b>Hello, {{ user.username }}.</b></span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'auctions:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                {% else %}
                <li class="nav-item pl-3">
                    <a class="nav-link border-left" href="{% url 'auctions:login' %}">Login</a>
                </li>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="flex-grow-1 bg-white">
        {% include 'auctions/messages.html' %}
        {% block body %}{% endblock %}
    </main>

    <section class="branding-section py-5 mt-5">
        <hr class="border-2 border-top mb-4" />
        <div class="container">
            <div class="row text-center text-md-start">
                <!-- Establishment -->
                <div class="col-md-3 mb-4">
                    <h5 class="text-uppercase fw-bold">Establishment</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-light">About Us</a></li>
                        <li><a href="#" class="text-light">Find Locations</a></li>
                    </ul>
                </div>
    
                <!-- Brand -->
                <div class="col-md-3 mb-4">
                    <h5 class="text-uppercase fw-bold">Brand</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-light">Press</a></li>
                        <li><a href="#" class="text-light">Blog</a></li>
                        <li><a href="#" class="text-light">Reviews</a></li>
                    </ul>
                </div>
    
                <!-- Support -->
                <div class="col-md-3 mb-4">
                    <h5 class="text-uppercase fw-bold">Support</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-light">Shipping/Return Policy</a></li>
                        <li><a href="#" class="text-light">Repairs</a></li>
                        <li><a href="#" class="text-light">Warranty</a></li>
                        <li><a href="#" class="text-light">FAQ</a></li>
                        <li><a href="#" class="text-light">Contact Us</a></li>
                    </ul>
                </div>
    
                <!-- Contact Us -->
                <div class="col-md-3 mb-4">
                    <h5 class="text-uppercase fw-bold">Contact Us</h5>
                    <ul class="list-unstyled">
                        <li><span class="d-block text-light"><i class="fa fa-phone"></i> 1-800-555-5555</span></li>
                        <li><span class="d-block text-light"><i class="fa fa-clock"></i> 9am-5pm EST, M-F</span></li>
                        <li><span class="d-block text-light"><i class="fa fa-clock"></i> 9am-1pm EST, Sat</span></li>
                        <li><span class="d-block text-light"><i class="fa fa-times"></i> Closed Sundays</span></li>
                    </ul>
                </div>
            </div>
    
            <hr class="my-4" />

            <!-- Subscription Form -->
            <div class="row text-center">
                <div class="col-md-6 mx-auto">
                    <form class="d-flex justify-content-center">
                        <input type="email" class="form-control me-2" placeholder="Enter your email here">
                        <button class="btn btn-primary" type="submit">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <footer class="bg-dark text-light text-center py-3">
        <div class="container">
            <p class="m-0">Angel Rodriguez &copy; {{ current_year }}</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>
</body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %} {% block body %} {% load static %} {% load humanize %}

<div class="container">
    <div class="row mt-5">
        <div class="col-lg-6 col-md-12 text-center">
            <a class="navbar-brand" href="{% url 'auctions:index' %}">
                <span class="display-1 font-weight-light fs-4 fs-md-3 responsive-title">
                    <span class="text-primary">Bid</span><span class="text-danger">stro</span><span class="text-warning">city</span>
                </span>
            </a>
            <p class="display-4 pt-3 text-primary">Login</p>
            <form action="{% url 'auctions:login' %}" method="POST">
                <div class="form-group">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" id="username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password">
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-primary btn-lg w-100">Sign In</button>
                <small>Not registered? You can register for an account <a
                        href="{% url 'auctions:register' %}">here</a>.</small>
            </form>
        </div>
        <div class="col-lg-6 col-md-12 mt-5">
            <img src="https://res.cloudinary.com/angelrodriguez/image/upload/v1608730069/cs50_commerce_project/Online_shopping_SVG.svg"
                class="img-fluid" alt="Responsive image">
        </div>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible text-center lighter" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}